### ISSUE TITLE
Rule suggestion: computed-property-even-spacing

### ISSUE THREAD

**Issue by xjamundx** [xjamundx/eslint-plugin-standard#1]
In case people want to `foo[ bar ]` or `foo[bar]`.

**Comment by dcousens** [comment]
@xjamundx :+1: looks good :)

**Comment by xjamundx** [comment]
done

**Comment by dcousens** [comment]
@feross is `foo[ bar ]` a thing?

**Comment by feross** [comment]
Not often, but some of the repos in the standard test suite do use it when there's a complicated expression in there, like this example from one of the npm repos:

```js
fs[ self.props.follow ? 'stat' : 'lstat' ](p, function (er, stat) {
  if (er) return self.error(er)
  ...
})
```

Maybe we should just disallow spaces... but I'd rather be conservative about changing the rules up on people, and enforcing consistency is a good start.

**Comment by dcousens** [comment]
@feross can we do a branch and maybe collect statistics on all `standard` dependents and compare the number of errors before and after following enabling/disabling of some rule?

**Comment by feross** [comment]
That's a neat idea. Sounds like quite a bit of work to implement, though.
