### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by feross** [xjamundx/eslint-plugin-standard#2]
Hey @xjamundx! I just updated this module to work with eslint 1.0.0.  I tried to publish a new version but don't have npm permission. Can you `npm owner add feross eslint-plugin-standard` or `npm publish`?

Also, can you confirm things look reasonable to you? https://github.com/xjamundx/eslint-plugin-standard/commits/master Thanks!!

**Comment by xjamundx** [comment]
Added you. I'm on `npm 3` and `publish` for me is broken :-p

**Comment by feross** [comment]
Heh, nice. Published 1.2.0.
