### ISSUE TITLE
Expected "null" instead of "undefined" in error position of callback

### ISSUE THREAD

**Issue by rschweizer** [xjamundx/eslint-plugin-standard#21]
After upgrading to the below versions of the respective packages I started to get the above error for the following code:

```(javascript)
callback(undefined, {
  statusCode: 200,
  body: JSON.stringify(data)
})
```

However, the rule descriptions states, that `undefined` should be valid? Can someone explain, why I get this error?

**Versions**:
eslint: 4.2.0
eslint-config-standard: 10.2.1
eslint-plugin-standard: 3.0.1

**Comment by xjamundx** [comment]
Code looks fine to me. I know null is more common, but I think we should
support undefined (and thought we did)

**Comment by julien-f** [comment]
I agree, `null` and `undefined` are a source of confusion and errors in JavaScript, I've personally started to use `undefined` everywhere but I hit this issue.

**Comment by xjamundx** [comment]
I can't remember if I'm supposed to publish these changes or if it's @feross . I'm a super bad maintainer.

**Comment by feross** [comment]
@xjamundx Hey, no worries! Either of us can publish a new version. This changes behavior so it should be a major version bump, and I'll need to manually version bump in `standard` to include it.

But please see my comment here: https://github.com/xjamundx/eslint-plugin-standard/pull/25#issuecomment-382532534

Also, would you mind transferring this to the @standard org for better visibility of issues/PRs?
